//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace telecomNevaSvyaz_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailableModule
    {
        public int AvailableModuleID { get; set; }
        public int ModuleID { get; set; }
        public int RoleID { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual Role Role { get; set; }
    }
}
